CREATE DATABASE DE01

USE DE01

--CAU 1-----------------
CREATE TABLE BAIHAT (
    MABH VARCHAR(4) PRIMARY KEY,
    TENBH VARCHAR(40),
    NAMST INT,
    THELOAI VARCHAR(20)
)
GO

CREATE TABLE NHACSI (
    MANS VARCHAR(4) PRIMARY KEY,
    TENNS VARCHAR(40),
    NGSINH SMALLDATETIME,
    SODT VARCHAR(20)
)
GO

CREATE TABLE SANGTAC (
    MABH VARCHAR(4),
    MANS VARCHAR(4),
    PRIMARY KEY (MABH, MANS),
    FOREIGN KEY (MABH) REFERENCES BAIHAT(MABH),
    FOREIGN KEY (MANS) REFERENCES NHACSI(MANS)
)
GO

CREATE TABLE PHATHANH (
    MABH VARCHAR(4),
    HINHTHUC VARCHAR(15),
    SL INT,
    NGPH SMALLDATETIME,
    PRIMARY KEY (MABH, HINHTHUC),
    FOREIGN KEY (MABH) REFERENCES BAIHAT(MABH)
)
GO

INSERT INTO BAIHAT VALUES
('BH01', 'Khi chung ta gia', 2013, 'Rock'),
('BH02', 'Chac ai do se ve', 2014, 'R&B'),
('BH03', 'Biet noi la tai sao?', 2014, 'Pop-ballad'),
('BH04', 'See tinh', 2022, 'Pop');

INSERT INTO NHACSI VALUES
('NS01', 'Son Tung MTP', '1994-07-05', '0905071994'),
('NS02', 'Khac Viet', '1987-08-30', '0930081987'),
('NS03', 'Pham Hong Phuoc', '1991-05-13', '0913051991'),
('NS04', 'Chau Dang Khoa', '1990-06-26', '0913054999');

INSERT INTO SANGTAC VALUES
('BH01', 'NS03'),
('BH01', 'NS01'),
('BH02', 'NS01'),
('BH03', 'NS02');

INSERT INTO PHATHANH VALUES
('BH01', 'Online', 7, '2014-03-07'),
('BH02', 'CD', 500, '2014-10-04'),
('BH03', 'MV', 20, '2014-11-09');


--CAU 2-----------------------------
--a---------------------------------
ALTER TABLE PHATHANH
ADD CONSTRAINT CK_HINHTHUC
CHECK (HINHTHUC IN ('Online', 'CD', 'MV'))
GO

--b---------------------------------
CREATE TRIGGER Trigger_PHATHANH_INSERT ON PHATHANH
FOR INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted I
        JOIN BAIHAT BH ON I.MABH = BH.MABH
        WHERE YEAR(I.NGPH) < BH.NAMST
    )

    BEGIN
        RAISERROR(N'Năm phát hành phải lớn hơn hoặc bằng năm sáng tác !!', 16, 1)
        ROLLBACK TRANSACTION
    END

END
GO

--CAU 3-----------------------------
--a---------------------------------
SELECT MABH, TENBH FROM BAIHAT
WHERE THELOAI = 'Pop-ballad'
ORDER BY TENBH ASC
GO

--b---------------------------------
SELECT BH.MABH, BH.TENBH FROM BAIHAT BH
JOIN SANGTAC ST ON BH.MABH = ST.MABH
JOIN NHACSI NS ON ST.MANS = NS.MANS
JOIN PHATHANH PH ON BH.MABH = PH.MABH
WHERE NS.TENNS = 'Son Tung MTP' AND PH.HINHTHUC = 'Online'
GO

--c---------------------------------
SELECT NS.MANS, NS.TENNS, BH.TENBH FROM NHACSI NS
LEFT JOIN SANGTAC ST ON NS.MANS = ST.MANS
LEFT JOIN BAIHAT BH ON ST.MABH = BH.MABH
GO

--d---------------------------------
SELECT DISTINCT NS.MANS, NS.TENNS FROM NHACSI NS
JOIN SANGTAC ST ON NS.MANS = ST.MANS
JOIN BAIHAT BH ON ST.MABH = BH.MABH
WHERE BH.NAMST = 2013

INTERSECT

SELECT DISTINCT NS.MANS, NS.TENNS FROM NHACSI NS
JOIN SANGTAC ST ON NS.MANS = ST.MANS
JOIN BAIHAT BH ON ST.MABH = BH.MABH
WHERE BH.NAMST = 2014

GO

--e---------------------------------
SELECT HINHTHUC, COUNT(MABH) AS SOLUONGBAIHATPHATHANH 
FROM PHATHANH 
GROUP BY HINHTHUC
GO

--f---------------------------------
SELECT NS.MANS, NS.TENNS, BH.MABH, BH.TENBH, PH.SL FROM NHACSI NS
JOIN SANGTAC ST ON NS.MANS = ST.MANS
JOIN BAIHAT BH ON ST.MABH = BH.MABH
JOIN PHATHANH PH ON BH.MABH = PH.MABH
WHERE BH.MABH IN (
		SELECT TOP 1 WITH TIES BH2.MABH FROM SANGTAC ST2
		JOIN BAIHAT BH2 ON ST2.MABH = BH2.MABH
		JOIN PHATHANH PH2 ON BH2.MABH = PH2.MABH
		WHERE ST2.MANS = ST.MANS
		ORDER BY PH2.SL DESC
	)
ORDER BY NS.MANS, BH.MABH
GO

--ALL BELOW FOR TESTING----------------
/*
DELETE FROM PHATHANH
DELETE FROM SANGTAC
DELETE FROM BAIHAT
DELETE FROM NHACSI

SELECT * FROM PHATHANH
SELECT * FROM SANGTAC
SELECT * FROM BAIHAT
SELECT * FROM NHACSI

DROP TABLE PHATHANH
DROP TABLE SANGTAC
DROP TABLE BAIHAT
DROP TABLE NHACSI
*/

--INSERT TO TEST----------------------
/*
INSERT INTO BAIHAT VALUES
('BH07', 'Di tim', 2013, 'Rock'),
('BH06', 'Tim lai', 2014, 'Rock'),
('BH05', 'Ngoi nhin chim troi', 2020, 'Rock'),
('BH01', 'Khi chung ta gia', 2013, 'Rock'),
('BH02', 'Chac ai do se ve', 2014, 'R&B'),
('BH03', 'Biet noi la tai sao?', 2014, 'Pop-ballad'),
('BH04', 'See tinh', 2022, 'Pop');

INSERT INTO NHACSI VALUES
('NS05', 'Nguyen Duc Trung', '2004-07-24', '0924072004'),
('NS02', 'Khac Viet', '1987-08-30', '0930081987'),
('NS03', 'Pham Hong Phuoc', '1991-05-13', '0913051991'),
('NS04', 'Chau Dang Khoa', '1990-06-26', '0913054999');

INSERT INTO SANGTAC VALUES
('BH06', 'NS05'),
('BH07', 'NS05'),
('BH05', 'NS05'),
('BH02', 'NS01'),
('BH03', 'NS02');

INSERT INTO PHATHANH VALUES
('BH05', 'Online', 465, '2020-03-07'),
('BH06', 'Online', 4, '2014-03-07'),
('BH07', 'Online', 100, '2014-03-07'),
('BH01', 'Online', 7, '2014-03-07'),
('BH02', 'CD', 500, '2014-10-04'),
('BH03', 'MV', 20, '2014-11-09');
*/