CREATE DATABASE CK_HK2_2020_2021

USE CK_HK2_2020_2021

-- 1. Bảng VACXIN
CREATE TABLE VACXIN (
    MAVX CHAR(5) PRIMARY KEY,
    TENVX NVARCHAR(50) NOT NULL,
    LOAIVX NVARCHAR(30) NOT NULL,
    MACTY CHAR(5) NOT NULL,
    HQLS DECIMAL(5,2) CHECK (HQLS BETWEEN 0 AND 100),
    HQTT DECIMAL(5,2) CHECK (HQTT BETWEEN 0 AND 100),
    SOMUI INT CHECK (SOMUI > 0),
    FOREIGN KEY (MACTY) REFERENCES CONGTY(MACTY)
)
GO

-- 2. Bảng CONGTY
CREATE TABLE CONGTY (
    MACTY CHAR(5) PRIMARY KEY,
    TENCTY NVARCHAR(50) NOT NULL,
    QUOCGIA NVARCHAR(30) NOT NULL,
    NAMTL INT CHECK (NAMTL >= 1800)  -- năm thành lập hợp lý
)
GO

-- 3. Bảng DIAPHUONG
CREATE TABLE DIAPHUONG (
    MADP CHAR(5) PRIMARY KEY,
    TENDP NVARCHAR(50) NOT NULL,
    SOF0 INT CHECK (SOF0 >= 0),
    SOTV INT CHECK (SOTV >= 0),
    DATIEM INT CHECK (DATIEM >= 0),
    TONGPB INT CHECK (TONGPB >= 0)
)
GO

-- 4. Bảng DATHANG
CREATE TABLE DATHANG (
    MADH CHAR(5) PRIMARY KEY,
    MAVX CHAR(5) NOT NULL,
    NOIDAT NVARCHAR(50) NOT NULL,
    SL INT CHECK (SL > 0),
    THGIAO DATE NOT NULL,
    TINHTRANG NVARCHAR(30) NOT NULL,
    FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
)
GO

-- 5. Bảng PHANBO
CREATE TABLE PHANBO (
    MADP CHAR(5) NOT NULL,
    MAVX CHAR(5) NOT NULL,
    DOT INT NOT NULL,
    SL INT CHECK (SL > 0),
    NGAYCAP DATE NOT NULL,
    PRIMARY KEY (MADP, MAVX, DOT),
    FOREIGN KEY (MADP) REFERENCES DIAPHUONG(MADP),
    FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
)
GO

--CAU--1--------------------------------------------

--CAU--2--------------------------------------------
--A-------
SELECT TENVX FROM VACXIN
WHERE LOAIVX = 'Vector virus' AND HQTT > 0.9
ORDER BY HQTT DESC
GO

--B------
SELECT D.MADH, D.SL FROM DATHANG D
JOIN VACXIN V ON D.MAVX = V.MAVX
WHERE V.LOAIVX = 'mRNA' 
	AND MONTH(D.THGIAO) = 8
	AND YEAR(D.THGIAO) = 2021
GO

--C------
SELECT DP.TENDP, COUNT(PB.DOT) AS SODOTCAP FROM PHANBO PB
JOIN DIAPHUONG DP ON PB.MADP = DP.MADP
WHERE MONTH(PB.NGAYCAP) = 6
	AND YEAR(PB.NGAYCAP) = 2021
GROUP BY DP.TENDP
GO

--D------
SELECT DP.MADP, DP.TENDP FROM DIAPHUONG DP
WHERE DP.SOF0 > 1000
	AND NOT EXISTS(
		SELECT 1 FROM PHANBO PB
		WHERE PB.MADP = DP.MADP
			AND YEAR(PB.NGAYCAP) = 2021 
	)
	GO

--E------
SELECT DP.MADP, DP.TENDP FROM DIAPHUONG DP
WHERE DP.SOF0 > 10000
	AND NOT EXISTS(
		SELECT * FROM CONGTY CT
		JOIN VACXIN VX ON CT.MACTY = VX.MACTY
		WHERE CT.TENCTY = 'Sinopharm'
			AND NOT EXISTS(
				SELECT * FROM PHANBO PB
				WHERE DP.TENDP = PB.MADP
				  AND PB.MAVX = VX.MAVX
			)
	)
	GO

--F-----
SELECT TOP 1 WITH TIES DP.MADP, DP.TENDP FROM DIAPHUONG DP
JOIN PHANBO PB ON DP.TENDP = PB.MADP
WHERE MONTH(PB.NGAYCAP) = 7
  AND YEAR(PB.NGAYCAP) = 2021
GROUP BY DP.MADP, DP.TENDP
ORDER BY COUNT(PB.MADP) DESC
GO