--Nguyen Duc Trung 
--22521564
--De thi thuc hanh HK1 Nam Hoc 2023-2024

CREATE DATABASE BTBuoi1

USE BTBuoi1

----Cau 1---------------
CREATE TABLE SINHVIEN(
	MaSV VARCHAR(10) PRIMARY KEY, 
	HoTen VARCHAR(50),
	NamSinh SMALLINT, 
	MaLop VARCHAR(10)
)
GO 

CREATE TABLE KHOA(
	MaKhoa VARCHAR(10) PRIMARY KEY, 
	TenKhoa VARCHAR(50)
)
GO

CREATE TABLE MON(
	MaMH VARCHAR(10) PRIMARY KEY, 
	TenMH VARCHAR(50), 
	SoTC TINYINT,
	MaKhoa VARCHAR(10) FOREIGN KEY REFERENCES KHOA(MaKhoa) 
)
GO 

CREATE TABLE DANGKY(
	MaSV VARCHAR(10) FOREIGN KEY REFERENCES SINHVIEN(MASV) ,
	MaMH VARCHAR(10) FOREIGN KEY REFERENCES MON(MaMH), 
	HocKy TINYINT, 
	NamHoc SMALLINT, 
	PRIMARY KEY(MaSV, MaMH, HocKy, NamHoc) 
)
GO

-----------------------------------------------------------
INSERT INTO SINHVIEN VALUES
('SV001', 'DAVID NOP', '2004', 'CE2022'),
('SV002', 'DAVID NGUYEN', '1999', 'CE2020');

INSERT INTO KHOA VALUES 
('HTTT01', 'He Thong Thong Tin'),
('CE01', 'Ky Thuat May Tinh'),
('CS01', 'Khoa Hoc May Tinh'),
('DS01', 'Khoa Hoc Du Lieu'); 

INSERT INTO DANGKY VALUES 
('SV001', 'MH01', 1, 2023);

INSERT INTO MON VALUES 
('MH01', 'DATABASE', 4, 'HTTT01');

/*
DROP TABLE KHOA
DROP TABLE SINHVIEN
DROP TABLE MON
DROP TABLE DANGKY

DELETE FROM MON
DELETE FROM KHOA
DELETE FROM SINHVIEN
DELETE FROM DANGKY
*/